---
required_apt_packages:
   - python
   - qemu-kvm
   - libvirt0
   - python-libvirt
   - virtinst
   - libvirt-bin
   - qemu-utils
   - ntp
   - htop
   - nload
   - vim
   - git
   - byobu
   - screen
   - smartmontools
   - mc
   - fping
   - genisoimage
   - lsscsi
   - usbview
   - bridge-utils
   - vlan
   - ifenslave
   - bmon
   - hdparm
   - iperf
   - iputils-arping
   - memtester
   - memtest86+
   - tcpdump
   - ifstat
   - nicstat
   - iftop
   - xfsprogs
   - parted
   - telnet
   - rsync
   - sysstat
   - procps
   - ntpdate
   - ntfs-3g
   - lvm2
   - lsof
   - mtr-tiny
   - traceroute
   - dnsutils
   - cpio
   - ethtool
   - htop
   - irqbalance
   - nmon
   - glances
   - mdadm
